### ISSUE TITLE
url-decode fails on very large files

### ISSUE THREAD

**Issue by za3k** [derhuerst/url-decode-encode-cli#3]
On a very large file (1GB), url-decode fails for me. A 100MB file (~10M lines) works fine for me.

```
/usr/local/lib/node_modules/url-decode-encode-cli/decode.js:13
        data += chunk.toString()
                      ^

RangeError: Invalid string length
    at ReadStream.process.stdin.on (/usr/local/lib/node_modules/url-decode-encode-cli/decode.js:13:16)
    at ReadStream.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at ReadStream.Readable.push (_stream_readable.js:224:10)
    at lazyFs.read (internal/fs/streams.js:181:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:467:17)
```

**Comment by derhuerst** [comment]
Thanks for reporting! Published as `url-decode-encode-cli@2.0.1`. 🎉
